# This file contains the default values for the cost calculations.

fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.07


#year for EUR outputs: 2015 is standard year in DEA, and DEA is NOT yet adjusted
# DEA takes for solar PV eur_year 2020!
