# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test PyPSA solar.csv

on:
  #workflow_dispatch:
  push:
    branches:
      - "adjust_hour_data"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pypsa
        python -m pip install pandas
        python -m pip install openpyxl
        python -m pip install gurobipy
        
    - shell: bash
      id: write-license
      env:
        LICENSE: ${{ secrets.GUROBI_LIC   }}
      run: |
        mkdir /opt/gurobi
        echo "$LICENSE" > /opt/gurobi/gurobi.lic
        # echo "grb_license_file=$PWD/gurobi.lic" >> $GITHUB_OUTPUT
        
    - name: Simple test
      run:
        python run_pypsa.py test_case.xlsx
        # Use the next line (instead of the above) to capture the run output for downloading later
        #python run_pypsa_bh.py > test_output.txt

    # Uncomment this section to upload output file(s) at the end of this job
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: my-artifact
    #    path: test_output.txt
